#!/bin/bash

MAX_NUM_SAMPLES=100000

#Sometimes need this
# --copy-column  "logweight_Romani_J1810" 

### add pressures, macroscopic values to CSV

NONPAR_EOS_DIR="/home/philippe.landry/gpr-eos-stacking/EoS/mrgagn"
PARAMETRIC_EOS_DIR="/home/isaac.legred/parametric-eos-priors/production_eos_draw_spectral/"
POST_DIR_5="/home/isaac.legred/ParametricPlotting/"


#TAGS="$TAGS qmc-hadagn-0.5rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.6rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.7rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.8rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.9rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-1.0rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-1.1rho_nuc-ingo-bps-3e11"

#TAGS="$TAGS mbpt-hadagn-0.5rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.6rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.7rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.8rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.9rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.0rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.1rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.2rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.3rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.4rho_nuc-ingo-bps-3e11"

#TAGS="$TAGS mrgagn-ingo-bps-1e10"



TAGS="corrected_original_post.csv corrected_parametric_post.csv"
EOS_DIR_TAGS="$NONPAR_EOS_DIR $PARAMETRIC_EOS_DIR"
EOS_PER_DIR="1000 200"
EOS_COUNT_ARR=($EOS_PER_DIR)
counter=0
for TAG in $TAGS
do
    EOS_DIRS=($EOS_DIR_TAGS)
    EOS_DIR=${EOS_DIRS[$counter]}
    INPATH=$POST_DIR_5$TAG
    echo $INPATH
    OUTPATH=$INPATH
    EOS_NUM_PER_DIR=${EOS_COUNT_ARR[$counter]}
    counter=$((counter+1))
    # look up pressures
    $(which process2samples) \
        $INPATH \
        $OUTPATH \
        baryon_density \
        pressurec2 energy_densityc2 \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
        --eos-num-per-dir ${EOS_NUM_PER_DIR} \
        --eos-basename 'eos-draw-%(draw)06d.csv' \
        --reference-value 1.4e14 \
        --reference-value 2.8e14 \
        --reference-value 4.2e14 \
        --reference-value 5.6e14 \
        --reference-value 8.4e14 \
        --reference-value 11.2e14 \
        --reference-value 16.8e14 \
        --max-num-samples $MAX_NUM_SAMPLES \
        --Verbose

    # look up macroscopic paramers
    $(which process2samples) \
        $OUTPATH \
        $OUTPATH \
        M \
        R Lambda \
        --nearest-neighbor \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
        --eos-num-per-dir ${EOS_NUM_PER_DIR} \
        --eos-basename 'macro-draw-%(draw)06d.csv' \
        --reference-value 1.0 \
        --reference-value 1.2 \
        --reference-value 1.4 \
        --reference-value 1.6 \
        --reference-value 1.8 \
        --reference-value 2.0 \
        --max-num-samples $MAX_NUM_SAMPLES \
        --Verbose


    # Get the max masses
    $(which process2extrema) \
        $OUTPATH \
	$OUTPATH \
        M \
        --copy-column  "logweight_LVC_GW190425_PhenomPNRThi" \
        --copy-column  "logweight_LVC_GW170817_PhenomPNRTlo" \
        --copy-column  "logweight_Antoniadis_J0348" \
        --copy-column  "logweight_Miller_J0030_threespot" \
        --copy-column  "logweight_Cromartie_J0740" \
        --copy-column  "logweight_total" \
        --copy-column  "pressurec2(baryon_density=1.4e+14)" \
        --copy-column  "pressurec2(baryon_density=2.8e+14)" \
        --copy-column  "pressurec2(baryon_density=4.2e+14)" \
        --copy-column  "pressurec2(baryon_density=5.6e+14)" \
        --copy-column  "pressurec2(baryon_density=8.4e+14)" \
        --copy-column  "pressurec2(baryon_density=1.12e+15)" \
        --copy-column  "pressurec2(baryon_density=1.68e+15)" \
        --copy-column  "energy_densityc2(baryon_density=1.4e+14)" \
        --copy-column  "energy_densityc2(baryon_density=2.8e+14)" \
        --copy-column  "energy_densityc2(baryon_density=4.2e+14)" \
        --copy-column  "energy_densityc2(baryon_density=5.6e+14)" \
        --copy-column  "energy_densityc2(baryon_density=8.4e+14)" \
        --copy-column  "energy_densityc2(baryon_density=1.12e+15)" \
        --copy-column  "energy_densityc2(baryon_density=1.68e+15)" \
        --copy-column  "R(M=1.0)" \
        --copy-column  "R(M=1.2)" \
        --copy-column  "R(M=1.4)" \
        --copy-column  "R(M=1.6)" \
        --copy-column  "R(M=1.8)" \
        --copy-column  "R(M=2.0)" \
        --copy-column  "Lambda(M=1.0)" \
        --copy-column  "Lambda(M=1.2)" \
        --copy-column  "Lambda(M=1.4)" \
        --copy-column  "Lambda(M=1.6)" \
        --copy-column  "Lambda(M=1.8)" \
        --copy-column  "Lambda(M=2.0)" \
        --new-column M Mmax Mmin \
        --column-range M 0.1 4.0 \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
	--eos-num-per-dir ${EOS_NUM_PER_DIR} \
	--eos-basename 'macro-draw-%(draw)06d.csv' \
	--max-num-samples $MAX_NUM_SAMPLES \
	--Verbose
done
