#!/bin/bash

MAX_NUM_SAMPLES=100000

#Sometimes need this
# --copy-column  "logweight_Romani_J1810" 


# These should be the only things that *need* to change
NONPAR_EOS_DIR="/home/philippe.landry/gpr-eos-stacking/EoS/mrgagn"
PARAMETRIC_EOS_DIR="/home/isaac.legred/parametric-eos-priors/good_gaussian_eos_draw_spectral/"
EOS_PER_DIR="1000 100"

# This may need to change if you change the overall convention
TAGS="/corrected_nonparametric_post.csv /corrected_parametric_post.csv"
# This is kinda a silly thing to do, but it will work for now
# Hardcode this if it's easier than worrying about where
# you call functions from
cd ../..
POST_DIR_5=$(pwd)
cd Utils/Plotting

#TAGS="$TAGS qmc-hadagn-0.5rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.6rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.7rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.8rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-0.9rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-1.0rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS qmc-hadagn-1.1rho_nuc-ingo-bps-3e11"

#TAGS="$TAGS mbpt-hadagn-0.5rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.6rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.7rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.8rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-0.9rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.0rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.1rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.2rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.3rho_nuc-ingo-bps-3e11"
#TAGS="$TAGS mbpt-hadagn-1.4rho_nuc-ingo-bps-3e11"

#TAGS="$TAGS mrgagn-ingo-bps-1e10"



EOS_DIR_TAGS="$NONPAR_EOS_DIR $PARAMETRIC_EOS_DIR"
EOS_COUNT_ARR=($EOS_PER_DIR)
counter=0
for TAG in $TAGS
do
    EOS_DIRS=($EOS_DIR_TAGS)
    EOS_DIR=${EOS_DIRS[$counter]}
    INPATH=$POST_DIR_5$TAG
    echo $INPATH
    OUTPATH=$INPATH
    EOS_NUM_PER_DIR=${EOS_COUNT_ARR[$counter]}
    counter=$((counter+1))
    # look up pressures
    $(which process2samples) \
        $INPATH \
        $OUTPATH \
        baryon_density \
        pressurec2 energy_densityc2 \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
        --eos-num-per-dir ${EOS_NUM_PER_DIR} \
        --eos-basename 'eos-draw-%(draw)06d.csv' \
        --reference-value 1.2e14 \
        --reference-value 2.4e14 \
        --reference-value 3.6e14 \
        --reference-value 4.8e14 \
        --reference-value 7.2e14 \
        --reference-value 1.44e15 \
        --reference-value 1.92e15 \
        --max-num-samples $MAX_NUM_SAMPLES \
        --Verbose

    # look up macroscopic paramers
    $(which process2samples) \
        $OUTPATH \
        $OUTPATH \
        M \
        R Lambda \
        --nearest-neighbor \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
        --eos-num-per-dir ${EOS_NUM_PER_DIR} \
        --eos-basename 'macro-draw-%(draw)06d.csv' \
        --reference-value 1.0 \
        --reference-value 1.2 \
        --reference-value 1.4 \
        --reference-value 1.6 \
        --reference-value 1.8 \
        --reference-value 2.0 \
        --max-num-samples $MAX_NUM_SAMPLES \
        --Verbose


    # Get the max masses
    $(which process2extrema) \
        $OUTPATH \
	$OUTPATH \
        M \
        --copy-column  "logweight_LVC_GW190425_PhenomPNRThi" \
        --copy-column  "logweight_LVC_GW170817_PhenomPNRTlo" \
        --copy-column  "logweight_Antoniadis_J0348" \
        --copy-column  "logweight_Miller_J0030_threespot" \
        --copy-column  "logweight_Cromartie_J0740" \
        --copy-column  "logweight_total" \
        --copy-column  "pressurec2(baryon_density=2.4e+14)" \
        --copy-column  "pressurec2(baryon_density=3.6e+14)" \
        --copy-column  "pressurec2(baryon_density=4.8e+14)" \
        --copy-column  "pressurec2(baryon_density=7.2e+14)" \
        --copy-column  "pressurec2(baryon_density=1.44e+15)" \
        --copy-column  "pressurec2(baryon_density=1.92e+15)" \
        --copy-column  "energy_densityc2(baryon_density=2.4e+14)" \
        --copy-column  "energy_densityc2(baryon_density=3.6e+14)" \
        --copy-column  "energy_densityc2(baryon_density=4.8e+14)" \
        --copy-column  "energy_densityc2(baryon_density=7.2e+14)" \
        --copy-column  "energy_densityc2(baryon_density=1.44e+14)" \
        --copy-column  "energy_densityc2(baryon_density=1.92e+15)" \
        --copy-column  "R(M=1.0)" \
        --copy-column  "R(M=1.2)" \
        --copy-column  "R(M=1.4)" \
        --copy-column  "R(M=1.6)" \
        --copy-column  "R(M=1.8)" \
        --copy-column  "R(M=2.0)" \
        --copy-column  "Lambda(M=1.0)" \
        --copy-column  "Lambda(M=1.2)" \
        --copy-column  "Lambda(M=1.4)" \
        --copy-column  "Lambda(M=1.6)" \
        --copy-column  "Lambda(M=1.8)" \
        --copy-column  "Lambda(M=2.0)" \
        --new-column M Mmax Mmin \
        --column-range M 0.1 4.0 \
        --eos-column eos \
        --eos-dir ${EOS_DIR} \
	--eos-num-per-dir ${EOS_NUM_PER_DIR} \
	--eos-basename 'macro-draw-%(draw)06d.csv' \
	--max-num-samples $MAX_NUM_SAMPLES \
	--Verbose
done
