#!/bin/bash

### test extracting quantiles
cd ../..
MAIN_DIR=$(pwd)
cd Utils/Plotting
export par_post=$MAIN_DIR"/parametric_post.csv"
export nonpar_post=$MAIN_DIR"/nonparametric_post.csv "
export eos_dir="/home/isaac.legred/parametric-eos-priors/production_eos_draw_spectral"
export eos_dir_nonpar="/home/philippe.landry/gpr-eos-stacking/EoS/mrgagn"
plot-process \
    pressurec2 \
    baryon_density \
    2.8e13 6.8e15 \
    --seed 123 \
    --logcolumn baryon_density \
    --column-label baryon_density '$\rho\ [\mathrm{g}/\mathrm{cm}^3]$' \
    --logcolumn pressurec2 \
    --column-label pressurec2 '$p\ [\mathrm{dyn}/\mathrm{cm}^2]$' \
    --y-multiplier c2 \
    --samples "PARAMETRIC(Pulsars)" $par_post \
    --samples "NONPARAMETRIC(Pulsars)" $nonpar_post\
    --max-num-samples "PARAMETRIC(Pulsars)" 70000 \
    --max-num-samples "NONPARAMETRIC(Pulsars)" 70000 \
    --weight-column "PARAMETRIC(Pulsars)" logweight_total \
    --weight-column-is-log "PARAMETRIC(Pulsars)" logweight_total \
    --weight-column "NONPARAMETRIC(Pulsars)" logweight_total \
    --weight-column-is-log "NONPARAMETRIC(Pulsars)" logweight_total \
    --include-neff \
    --color "PARAMETRIC(Pulsars)" b \
    --eos-column "PARAMETRIC(Pulsars)" eos \
    --eos-dir "PARAMETRIC(Pulsars)" $eos_dir \
    --eos-num-per-dir "PARAMETRIC(Pulsars)" 200 \
    --eos-basename "PARAMETRIC(Pulsars)" 'eos-draw-%(draw)06d.csv' \
    --color "NONPARAMETRIC(Pulsars)" r \
    --eos-column "NONPARAMETRIC(Pulsars)" eos \
    --eos-dir "NONPARAMETRIC(Pulsars)" $eos_dir_nonpar \
    --eos-num-per-dir "NONPARAMETRIC(Pulsars)" 1000 \
    --eos-basename "NONPARAMETRIC(Pulsars)" 'eos-draw-%(draw)06d.csv' \
    --num-points 50 \
    --quantile 0.05 --quantile 0.25 \
    --legend \
    --output-dir $POST_DIR \
    --figwidth 12 \
    --figheight 8 \
    --Verbose
